name: Update README ✍️

# Run hourly
on:
  push:
    branches: [main]
  schedule:
    - cron: "0 */1 * * *"
  workflow_dispatch:

jobs:
  readme-scribe:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Generate README.md
        uses: muesli/readme-scribe@v0.1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        with:
          template: "templates/README.md.tpl"
          writeTo: "README.md"
      - name: Commit README.md
        uses: stefanzweifel/git-auto-commit-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: "docs: update README.md"
          branch: main
          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com
          commit_author: GitHub Actions <actions@github.com>
      - name: Push README.md to wimpysworld/.github/profile
        uses: nkoppel/push-files-to-another-repository@v1.1.3
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          commit-username: 'GitHub Actions'
          commit-email: 'actions@github.com'
          commit-message: 'docs: sync README'
          destination-branch: 'main'
          destination-directory: 'profile/'
          destination-repository: '.github'
          destination-username: 'wimpysworld'
          source-files: README.md
